version: '3'
services:

  jobmanager:
    # network_mode: "host"
    image: flink:1.14.0-scala_2.11-java11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - data:/mnt/data
    networks:
      - kafka
      - default

  taskmanager:
    image: flink:1.14.0-scala_2.11-java11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - data:/mnt/data
    networks:
      - kafka
      - default

volumes:
  # This volume will show with 'docker volume ls' as 'docker_data'
  data:

networks:
  kafka:
    external: true